version: "3.3"
services:
  mysql:
    build: ./docker/mysql
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
      MYSQL_ROOT_PASSWORD: redmine
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
  postgresql:
    build: ./docker/postgres
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=ja_JP.UTF-8"
    command: 'postgres -c config_file="/etc/postgresql/postgresql.conf"'
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/postgres/conf.d:/etc/postgresql
      - ./log/postgres:/var/log/postgresql
